src/screen-templates/full-screen.json
src/screen-templates/three-boxes-horizontal.json
src/screen-templates/three-boxes.json
src/screen-templates/touch-template.json
src/screen-templates/two-boxes.json

https://jira.itkdev.dk/browse/AR-738

AR-738: added screen templates

---

src/image-text/image-text-admin.json
src/slides.js

https://jira.itkdev.dk/browse/AR-737

AR-737: error fixes

---

src/book-review/book-review.json
src/image-text/image-text.json
src/slideshow/slideshow.json

https://jira.itkdev.dk/browse/AR-754

AR-754: added ids to templates

---

src/image-text/image-text.scss

https://jira.itkdev.dk/browse/AR-737

AR-737: added margin to test in image-text

---

src/themes/aarhus.css
src/themes/dokk1.css
src/themes/mso.css

https://jira.itkdev.dk/browse/AR-736
Add theme css in files in the folder Themes.
To use the css, copy the contents of the file, and paste it in the Theme css field in the admin frontend.

AR-736: Basic themes

---

src/book-review/book-review-admin.json
src/image-text/image-text-admin.json
src/slideshow/slideshow-admin.json

https://jira.itkdev.dk/browse/AR-611

AR-611: changed label

---

build/calendar/calendar-admin.json
build/instagram-feed/instagram-feed-admin.json
build/poster/poster-admin.json
build/rss/rss-admin.json
src/calendar/calendar-admin.json
src/instagram-feed/instagram-feed-admin.json
src/poster/poster-admin.json
src/rss/rss-admin.json

https://jira.itkdev.dk/browse/AR-802
Changes feedType to supportedFeedType.

AR-802: Changed feedType to supportedFeedType

---

src/slides.js
src/themes/dokk1.css

AR-825: Add font-family on slide root.

---

build/book-review-config-develop.json
build/book-review-config-main.json
build/calendar-config-develop.json
build/calendar-config-main.json
build/contacts-config-develop.json
build/contacts-config-main.json
build/iframe-config-develop.json
build/iframe-config-main.json
build/image-text-config-develop.json
build/image-text-config-main.json
build/instagram-feed-config-develop.json
build/instagram-feed-config-main.json
build/poster-config-develop.json
build/poster-config-main.json
build/rss-config-develop.json
build/rss-config-main.json
build/slideshow-config-develop.json
build/slideshow-config-main.json
build/table-config-develop.json
build/table-config-main.json
build/travel-config-develop.json
build/travel-config-main.json
build/video-config-develop.json
build/video-config-main.json
webpack.config.js

Adds a timestamp paths in "{template}-config-{env}.json" files to ensure new code is loaded when the template is reimported.

AR-858: Added timestamp to template paths

---

package.json
src/index.css
src/index.js
src/screen-layouts/six-areas.json
src/screen-layouts/touch-template.json
src/screens.js
yarn.lock

https://jira.itkdev.dk/browse/AR-871

AR-871: make touch and six area layout more fine grained

---

src/themes/aakb.css

https://jira.itkdev.dk/browse/AR-880
Add book-review styling to aakb theme

AR-880: Add book-review styling to aakb theme

---

CHANGELOG.md
src/index.js
src/screen-layouts/four-areas.json
src/screens.js

[ git push --set-upstream origin feature/AR-893-add-four-area-screen-template
](https://jira.itkdev.dk/browse/AR-893)

AR-893: add four areas screen template

---

CHANGELOG.md
src/screen-layouts/six-areas.json

rename titles in screen templates

---

CHANGELOG.md
build/calendar-admin.json
build/calendar-config-develop.json
build/calendar-config-main.json
build/image-text-admin.json
build/image-text-config-develop.json
build/image-text-config-main.json
build/table-admin.json
build/table-config-develop.json
build/table-config-main.json
src/calendar/calendar-admin.json
src/image-text/image-text-admin.json
src/table/table-admin.json

https://jira.itkdev.dk/browse/AR-931
Changed admin forms values from .font-size-l to .font-size-lg.

AR-931: Fixed font-size-lg

---

CHANGELOG.md
src/themes/aakb.css

Remove colored background in reversed option

AR-937: Fix reversed layout background

---

CHANGELOG.md
build/image-text-admin.json
build/image-text-config-develop.json
build/image-text-config-main.json
src/image-text/image-text-admin.json

https://jira.itkdev.dk/browse/AR-941
Changed admin texts

AR-941: Changed admin texts

---

CHANGELOG.md
build/calendar-config-develop.json
build/calendar-config-main.json
src/calendar/calendar-multiple-days.js
src/calendar/calendar.js

https://jira.itkdev.dk/browse/AR-940
* Fixed calendar event sorting

AR-940: Fixed calendar event sorting

---

CHANGELOG.md
src/themes/aakb.css

https://jira.itkdev.dk/browse/AR-942
Result:

AR-942: Styling fixes

---

CHANGELOG.md
src/themes/blixen.css

https://jira.itkdev.dk/browse/AR-924
Changed how font is loaded

AR-924: Changed how font is loaded

---

CHANGELOG.md
src/themes/dokk1.css

Dokk1 theme file.
Change seperator color to white

Change seperator color to white

---

CHANGELOG.md
src/poster/poster.scss

https://jira.itkdev.dk/browse/DISPLAY-923

DISPLAY-923: change background color, position of logo

---

CHANGELOG.md
src/screen-layouts/two-boxes-vertical-reversed.json
src/screens.js

https://jira.itkdev.dk/browse/SUPP0RT-1020

SUPP0RT-1020: add new screen template

---

CHANGELOG.md
README.md
webpack.config.js
yarn.lock

https://jira.itkdev.dk/browse/DISPLAY-1030
Improvements for building during development.

DISPLAY-1030: Improved build for local development

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Added github PR template
